# Generated by Django 6.0.3 on 2026-03-24 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sociallink',
            index=models.Index(fields=['user_id', 'provider'], name='social_link_user_id_8a4a9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together={('user', 'provider')},
        ),
    ]
