# Generated by Django 4.2.11 on 2026-04-27 12:10

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_deleted_recipe_and_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="food_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("grain", "Зерновые"),
                    ("protein", "Белки"),
                    ("vegetable", "Овощи"),
                    ("fruit", "Фрукты"),
                    ("dairy", "Молочные"),
                    ("oil", "Масла/жиры"),
                    ("other", "Прочее"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="grain_type",
            field=models.CharField(
                blank=True,
                choices=[("whole", "Цельнозерновые"), ("refined", "Рафинированные")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_fatty_fish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_red_meat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="protein_type",
            field=models.CharField(
                blank=True,
                choices=[("animal", "Животный"), ("plant", "Растительный"), ("mixed", "Смешанный")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="suitable_for",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["food_group"], name="recipes_food_gr_3866f6_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["protein_type"], name="recipes_protein_3c5ee4_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["grain_type"], name="recipes_grain_t_3c1714_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["is_fatty_fish"], name="recipes_is_fatt_7d869a_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["is_red_meat"], name="recipes_is_red__a496bb_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=django.contrib.postgres.indexes.GinIndex(fields=["suitable_for"], name="recipe_suitable_for_gin"),
        ),
    ]
