# Generated by Django 4.2.11 on 2026-04-28 15:01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_food_group_recipe_grain_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="povar_raw",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
