# Generated by Django 4.2.11 on 2026-05-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_recipe_kbju"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="kcal",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Калорийность на 1 порцию, ккал (MG-104d-4).",
                max_digits=7,
                null=True,
            ),
        ),
    ]
