# Generated by Django 4.2.11 on 2026-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_recipe_servings_normalized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="servings_normalized",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Нормализованное число порций (MG-104d-5)", null=True
            ),
        ),
    ]
