# Generated by Django 4.2.11 on 2026-05-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_alter_recipe_servings_normalized"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cooking_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("boiled", "Варёное"),
                    ("baked", "Запечённое"),
                    ("fried", "Жареное"),
                    ("grilled", "Гриль"),
                    ("raw", "Сырое"),
                    ("stewed", "Тушёное"),
                    ("steamed", "На пару"),
                ],
                help_text="Метод приготовления (MG-501).",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="has_added_sugar",
            field=models.BooleanField(default=False, help_text="Содержит добавленный сахар (MG-501)."),
        ),
        migrations.AddField(
            model_name="recipe",
            name="oil_tsp",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Расход масла в чайных ложках (MG-501).",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="serving_size_label",
            field=models.CharField(
                blank=True,
                help_text='Подпись размера порции, напр. "1 тарелка / 200 г" (MG-501).',
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["cooking_method"], name="recipes_cooking_b07451_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["has_added_sugar"], name="recipes_has_add_0fb612_idx"),
        ),
    ]
