# Generated by Django 4.2.11 on 2026-05-17 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0010_mg_501_recipe_classification"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_favorite", models.BooleanField(default=True, help_text="True=любимое, False=нелюбимое")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="favorites", to="recipes.recipe"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recipe_favorites",
                "indexes": [
                    models.Index(fields=["user", "is_favorite"], name="recipe_favo_user_id_d06590_idx"),
                    models.Index(fields=["recipe"], name="recipe_favo_recipe__8b3350_idx"),
                ],
                "unique_together": {("user", "recipe")},
            },
        ),
    ]
