# Generated by Django 4.2.11 on 2026-05-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_recipe_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedRecipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_id", models.IntegerField(db_index=True)),
                ("title", models.CharField(max_length=512)),
                ("data", models.JSONField(help_text="Полный снимок полей рецепта на момент архивации.")),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "archived_recipes",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="allergens",
            field=models.JSONField(blank=True, default=list, help_text="Список аллергенов. RB-001."),
        ),
        migrations.AddField(
            model_name="recipe",
            name="carbs_per_100g",
            field=models.DecimalField(
                blank=True, decimal_places=1, help_text="Углеводы на 100 г. RB-001.", max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cook_time_min",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Время приготовления, мин (число). RB-001.", null=True
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="dish_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soup", "Первое (суп)"),
                    ("main", "Второе/горячее"),
                    ("salad", "Салат"),
                    ("side", "Гарнир"),
                    ("dessert", "Десерт"),
                    ("drink", "Напиток/компот"),
                    ("bakery", "Выпечка"),
                    ("sauce", "Соус"),
                    ("snack", "Перекус"),
                    ("breakfast_dish", "Завтрак-блюдо"),
                ],
                help_text="Тип блюда (первое/второе/десерт...). RB-001.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="fats_per_100g",
            field=models.DecimalField(
                blank=True, decimal_places=1, help_text="Жиры на 100 г. RB-001.", max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_gluten_free",
            field=models.BooleanField(default=False, help_text="Без глютена. RB-001."),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_lactose_free",
            field=models.BooleanField(default=False, help_text="Без лактозы. RB-001."),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_vegan",
            field=models.BooleanField(default=False, help_text="Веганское. RB-001."),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_vegetarian",
            field=models.BooleanField(default=False, help_text="Вегетарианское. RB-001."),
        ),
        migrations.AddField(
            model_name="recipe",
            name="kcal_per_100g",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Калорийность на 100 г готового блюда. RB-001.",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="portion_g",
            field=models.PositiveIntegerField(blank=True, help_text="Вес одной порции, г. RB-001.", null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="proteins_per_100g",
            field=models.DecimalField(
                blank=True, decimal_places=1, help_text="Белки на 100 г. RB-001.", max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="source",
            field=models.CharField(
                choices=[
                    ("own", "Собственный"),
                    ("import", "Импорт"),
                    ("user", "Пользовательский"),
                    ("parsed", "Спарсенный"),
                ],
                default="own",
                help_text="Источник рецепта. RB-001.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="sugars_per_100g",
            field=models.DecimalField(
                blank=True, decimal_places=1, help_text="Сахара на 100 г. RB-001.", max_digits=6, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["dish_type"], name="recipes_dish_ty_05ba23_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["source"], name="recipes_source_e8c194_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["is_vegan"], name="recipes_is_vega_a4acf6_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["is_vegetarian"], name="recipes_is_vege_8abf61_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["is_gluten_free"], name="recipes_is_glut_408cf4_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["is_lactose_free"], name="recipes_is_lact_e981a8_idx"),
        ),
        migrations.AddIndex(
            model_name="archivedrecipe",
            index=models.Index(fields=["original_id"], name="archived_re_origina_2a1d2e_idx"),
        ),
    ]
