# Generated by Django 4.2.11 on 2026-06-01 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0013_cuisine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuisine",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.CreateModel(
            name="RecipeImportSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uploaded_file", models.FileField(upload_to="recipe_imports/", verbose_name="Файл xlsx")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Загружен"),
                            ("preview", "Превью готово"),
                            ("done", "Импортировано"),
                            ("error", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("preview_data", models.JSONField(blank=True, default=list, verbose_name="Данные превью")),
                ("parse_errors", models.JSONField(blank=True, default=list, verbose_name="Ошибки парсинга")),
                ("warnings", models.JSONField(blank=True, default=list, verbose_name="Предупреждения")),
                ("recipes_count", models.PositiveIntegerField(default=0, verbose_name="Рецептов к импорту")),
                ("imported_count", models.PositiveIntegerField(default=0, verbose_name="Импортировано")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия импорта рецептов",
                "verbose_name_plural": "Импорт рецептов (сессии)",
                "db_table": "recipe_import_sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
