# Generated by Django 4.2.11 on 2026-06-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_recipeproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="plate_component",
            field=models.CharField(
                blank=True,
                choices=[("protein", "Plate: protein"), ("carb", "Plate: carb (side)"), ("veg", "Plate: veg/fiber")],
                help_text="Plate component for strategy=3 (manual tagging).",
                max_length=8,
                null=True,
            ),
        ),
    ]
