# Generated by Django 4.2.11 on 2026-07-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0017_recipe_allergens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="allergens",
            field=models.JSONField(blank=True, default=list, help_text="Список аллергенов. RB-001."),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image_url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="source_url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="video_url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
