# Generated by Django 4.2.11 on 2026-08-04 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0019_recipemadephoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="recipes/gallery/", verbose_name="Фото")),
                ("caption", models.CharField(blank=True, max_length=255, verbose_name="Подпись")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="gallery_images", to="recipes.recipe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото рецепта",
                "verbose_name_plural": "Фото рецепта",
                "db_table": "recipe_images",
                "ordering": ["sort_order", "id"],
                "indexes": [models.Index(fields=["recipe", "sort_order"], name="recipe_imag_recipe__de1a10_idx")],
            },
        ),
    ]
