# Generated by Django 6.0.3 on 2026-03-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('title', models.CharField(max_length=512)),
                ('cook_time', models.CharField(blank=True, max_length=64, null=True)),
                ('servings', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ingredients', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('nutrition', models.JSONField(default=dict)),
                ('categories', models.JSONField(default=list)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('video_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20)),
                ('motivation_text', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('recipes_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'recipe_authors',
            },
        ),
    ]
