# Generated by Django 6.0.3 on 2026-03-24 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeauthor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['legacy_id'], name='recipes_legacy__fccf35_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['country'], name='recipes_country_3bbbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['author_id'], name='recipes_author__745c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_custom'], name='recipes_is_cust_1d54fa_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_published'], name='recipes_is_publ_d405bb_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeauthor',
            index=models.Index(fields=['user_id'], name='recipe_auth_user_id_b07bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeauthor',
            index=models.Index(fields=['status'], name='recipe_auth_status_c1c6fe_idx'),
        ),
    ]
