# Generated by Django 4.2.11 on 2026-04-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="carbs_target_g",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="fat_target_g",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="fiber_target_g",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="meal_plan",
            field=models.CharField(
                choices=[("3", "3 приёма пищи"), ("5", "5 приёмов пищи")], default="3", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="protein_target_g",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
