# Generated by Django 4.2.11 on 2026-05-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_carbs_target_g_profile_fat_target_g_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="carbs_target_g",
            new_name="carb_target_g",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="meal_plan",
            new_name="meal_plan_type",
        ),
    ]
