# Generated by Django 4.2.11 on 2026-05-04 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_carbs_target_g_profile_carb_target_g_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileTargetAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("calorie_target", "calorie_target"),
                            ("protein_target_g", "protein_target_g"),
                            ("fat_target_g", "fat_target_g"),
                            ("carb_target_g", "carb_target_g"),
                            ("fiber_target_g", "fiber_target_g"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("auto", "auto"), ("user", "user"), ("specialist", "specialist")], max_length=16
                    ),
                ),
                ("old_value", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("new_value", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_target_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="target_audits", to="users.profile"
                    ),
                ),
            ],
            options={
                "db_table": "profile_target_audit",
                "ordering": ["-at"],
                "indexes": [models.Index(fields=["profile", "field", "-at"], name="profile_tar_profile_2d4551_idx")],
            },
        ),
    ]
