# Generated by Django 4.2.11 on 2026-05-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profiletargetaudit"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bedtime_hour",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Час отхода ко сну (0-23) для правила «не есть за 3ч до сна»", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="cheat_meal_interval",
            field=models.PositiveSmallIntegerField(default=10, help_text="Интервал в днях между cheat-meal приёмами"),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_cheat_meal_date",
            field=models.DateField(
                blank=True, help_text="Дата последнего cheat-meal — обновляется генератором", null=True
            ),
        ),
    ]
