# Generated by Django 4.2.11 on 2026-07-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_grandfather_email_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneVerification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(max_length=20)),
                (
                    "provider",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("max", "Max")], default="telegram", max_length=16
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("verified", "Подтверждён"),
                            ("mismatch", "Номер не совпал"),
                            ("consumed", "Использован (регистрация завершена)"),
                            ("expired", "Истёк"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("chat_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("messenger_user_id", models.CharField(blank=True, max_length=64, null=True)),
                ("messenger_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "phone_verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="phone_verif_token_a97c45_idx"),
                    models.Index(fields=["phone", "status"], name="phone_verif_phone_8248f8_idx"),
                ],
            },
        ),
    ]
