# Generated by Django 4.2.11 on 2026-08-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_phoneverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
