# Generated by Django 4.2.11 on 2026-09-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0006_family_auto_expiry"),
        ("users", "0011_user_deletion_requested_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="family.family",
            ),
        ),
    ]
