# Generated by Django 4.2.11 on 2026-09-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_active_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="head_may_edit_diary",
            field=models.BooleanField(
                default=False, help_text="Разрешить главе семьи править и удалять мои записи (MG_HEADKEEPS)."
            ),
        ),
    ]
