# Generated by Django 6.0.3 on 2026-03-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('month', 'Месяц'), ('year', 'Год')], default='month', max_length=10)),
                ('features', models.JSONField(default=dict)),
                ('max_family_members', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'subscription_plans',
                'indexes': [models.Index(fields=['code'], name='subscriptio_code_e250fc_idx'), models.Index(fields=['is_active'], name='subscriptio_is_acti_4d4352_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена'), ('expired', 'Истекла'), ('trial', 'Пробный период')], default='active', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='family.family')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
            ],
            options={
                'db_table': 'subscriptions',
                'indexes': [models.Index(fields=['family_id', 'status'], name='subscriptio_family__13a37f_idx'), models.Index(fields=['expires_at'], name='subscriptio_expires_af5d7e_idx')],
            },
        ),
    ]
