# Generated by Django 4.2.11 on 2026-05-11 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0008_menuitem_is_cheat_meal"),
        ("diary", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="is_eaten",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diaryentry",
            name="planned_menu_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diary_entries",
                to="menu.menuitem",
                unique=True,
            ),
        ),
    ]
