# Generated by Django 4.2.11 on 2026-05-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0008_menuitem_is_cheat_meal"),
        ("diary", "0004_planned_menu_item_is_eaten"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="planned_menu_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diary_entry",
                to="menu.menuitem",
            ),
        ),
    ]
