# Generated by Django 4.2.11 on 2026-08-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0005_family_currency"),
        ("diary", "0006_diaryentry_is_planned"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("weight_kg", models.DecimalField(decimal_places=1, max_digits=5)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_logs",
                        to="family.familymember",
                    ),
                ),
            ],
            options={
                "db_table": "weight_logs",
                "ordering": ["-date"],
                "indexes": [models.Index(fields=["member_id", "-date"], name="weight_logs_member__936f43_idx")],
                "unique_together": {("member", "date")},
            },
        ),
    ]
