# Generated by Django 4.2.11 on 2026-09-07 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0006_family_auto_expiry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diary", "0007_weightlog"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="waterlog",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="weightlog",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="diaryentry",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diary_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="waterlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="water_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="weightlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weight_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diary_entries",
                to="family.familymember",
            ),
        ),
        migrations.AlterField(
            model_name="waterlog",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="water_logs",
                to="family.familymember",
            ),
        ),
        migrations.AlterField(
            model_name="weightlog",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weight_logs",
                to="family.familymember",
            ),
        ),
        # MG_OWNDIARY: уникальность по (user, date) ставится не здесь, а в 0010 —
        # после того, как 0009 заполнит владельца и разберёт задвоенные дни.
        # Поставить её раньше нельзя: пока колонка пуста, ограничение пройдёт (в
        # Postgres NULL'ы друг с другом не конфликтуют) и упадёт в середине
        # заполнения, оставив половину строк без владельца.
        migrations.AddIndex(
            model_name="diaryentry",
            index=models.Index(fields=["user_id", "date"], name="diary_entri_user_id_316c41_idx"),
        ),
        migrations.AddIndex(
            model_name="weightlog",
            index=models.Index(fields=["user_id", "-date"], name="weight_logs_user_id_01dce6_idx"),
        ),
    ]
