# Generated by Django 4.2.11 on 2026-09-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0011_meal_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="grams",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
