# Generated by Django 4.2.11 on 2026-04-23 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0003_familymember_can_edit_menu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("menu_id", models.IntegerField(db_index=True)),
                ("data", models.JSONField()),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("purge_after", models.DateTimeField()),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="deleted_menus", to="family.family"
                    ),
                ),
            ],
            options={
                "db_table": "deleted_menus",
                "ordering": ["-deleted_at"],
            },
        ),
    ]
