# Generated by Django 4.2.11 on 2026-04-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0004_remove_familymember_can_edit_menu"),
        ("menu", "0003_deletedmenu"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="menuitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_salad",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="menuitem",
            unique_together={("menu", "member", "day_offset", "meal_type", "is_salad")},
        ),
    ]
