# Generated by Django 4.2.11 on 2026-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_menu_warnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_cheat_meal",
            field=models.BooleanField(default=False),
        ),
    ]
