# Generated by Django 4.2.11 on 2026-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0008_menuitem_is_cheat_meal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="component_role",
            field=models.CharField(
                choices=[
                    ("breakfast_dish", "Завтрак-блюдо"),
                    ("soup", "Первое (суп)"),
                    ("main", "Второе/горячее"),
                    ("salad", "Салат"),
                    ("side", "Гарнир"),
                    ("dessert", "Десерт"),
                    ("drink", "Напиток"),
                    ("bakery", "Выпечка"),
                    ("sauce", "Соус"),
                    ("snack", "Перекус"),
                    ("other", "Прочее"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
