# Generated by Django 4.2.11 on 2026-07-23 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0005_family_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0019_recipemadephoto"),
        ("menu", "0009_rb001_step4_component_role_dish_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructedMeal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day_index", models.PositiveSmallIntegerField(default=0)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("name", models.CharField(max_length=100)),
                ("target_calories", models.PositiveIntegerField(blank=True, null=True)),
                ("target_protein", models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ("target_fat", models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ("target_carbs", models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
            ],
            options={
                "db_table": "constructed_meals",
                "ordering": ["day_index", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ConstructedMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("days", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Готово")], default="draft", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constructed_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="constructed_menus",
                        to="family.family",
                    ),
                ),
            ],
            options={
                "db_table": "constructed_menus",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConstructedMealItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="menu.constructedmeal"
                    ),
                ),
                ("recipe", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe")),
            ],
            options={
                "db_table": "constructed_meal_items",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="constructedmeal",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="meals", to="menu.constructedmenu"
            ),
        ),
        migrations.AddIndex(
            model_name="constructedmenu",
            index=models.Index(fields=["author_id"], name="constructed_author__e62e75_idx"),
        ),
        migrations.AddIndex(
            model_name="constructedmenu",
            index=models.Index(fields=["client_family_id"], name="constructed_client__44373b_idx"),
        ),
        migrations.AddIndex(
            model_name="constructedmealitem",
            index=models.Index(fields=["meal_id"], name="constructed_meal_id_e054c1_idx"),
        ),
        migrations.AddIndex(
            model_name="constructedmeal",
            index=models.Index(fields=["menu_id", "day_index"], name="constructed_menu_id_14c68a_idx"),
        ),
    ]
