# Generated by Django 4.2.11 on 2026-07-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fridge", "0015_product_owner_product_products_owner_i_8cc6ea_idx"),
        ("recipes", "0019_recipemadephoto"),
        ("menu", "0010_constructedmeal_constructedmenu_constructedmealitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructedmealitem",
            name="grams",
            field=models.PositiveIntegerField(
                blank=True, help_text="Порция продукта-блюда, г (MG_PRODDISH).", null=True
            ),
        ),
        migrations.AddField(
            model_name="constructedmealitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constructed_meal_items",
                to="fridge.product",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="grams",
            field=models.PositiveIntegerField(
                blank=True, help_text="Порция продукта-блюда, г (MG_PRODDISH).", null=True
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="fridge.product",
            ),
        ),
        migrations.AlterField(
            model_name="constructedmealitem",
            name="recipe",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="recipe",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
            ),
        ),
    ]
