# Generated by Django 4.2.11 on 2026-08-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0011_constructedmealitem_grams_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructedmenu",
            name="applied_menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="from_constructed",
                to="menu.menu",
            ),
        ),
    ]
