# Generated by Django 6.0.3 on 2026-03-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('default_unit', models.CharField(blank=True, max_length=50)),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('nutrition', models.JSONField(default=dict)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['category'], name='products_categor_fce6e6_idx'), models.Index(fields=['barcode'], name='products_barcode_d008ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('added_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_items', to='family.family')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fridge.product')),
            ],
            options={
                'db_table': 'fridge_items',
                'indexes': [models.Index(fields=['family_id'], name='fridge_item_family__330b0b_idx'), models.Index(fields=['product_id'], name='fridge_item_product_9fcc96_idx'), models.Index(fields=['expiry_date'], name='fridge_item_expiry__eb0e80_idx'), models.Index(fields=['is_deleted'], name='fridge_item_is_dele_e73231_idx')],
            },
        ),
    ]
