# Generated by Django 4.2.11 on 2026-07-16 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0005_family_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0003_create_free_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Срок подписки в днях. Пусто — берётся период плана (месяц/год).",
                        null=True,
                    ),
                ),
                (
                    "max_redemptions",
                    models.PositiveIntegerField(
                        default=1, help_text="Сколько раз код можно активировать (1 — одноразовый)."
                    ),
                ),
                ("redeemed_count", models.PositiveIntegerField(default=0)),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="До какого момента код можно активировать. Пусто — без ограничения по дате.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "campaign",
                    models.CharField(
                        blank=True, default="", help_text="Метка кампании/партии (для админки).", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promo_codes",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "promo_codes",
            },
        ),
        migrations.CreateModel(
            name="PromoRedemption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_redemptions",
                        to="family.family",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="subscriptions.promocode",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promo_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promo_redemptions",
                "indexes": [models.Index(fields=["family"], name="promo_redem_family__876fad_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="promoredemption",
            constraint=models.UniqueConstraint(fields=("promo", "family"), name="uniq_promo_family"),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(fields=["code"], name="promo_codes_code_5b1d05_idx"),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(fields=["is_active"], name="promo_codes_is_acti_856e08_idx"),
        ),
    ]
