# Generated by Django 4.2.11 on 2026-07-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_promocode_promoredemption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="assigned_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Если задан — активировать код может только пользователь с этим email.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="owner",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Владелец ключа: имя или компания (для именных ключей).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="promoredemption",
            name="revoke_mode",
            field=models.CharField(
                blank=True,
                choices=[("", "—"), ("free", "Переведён на бесплатный тариф"), ("block", "Пользователь заблокирован")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="promoredemption",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
