# Generated by Django 4.2.11 on 2026-07-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_promocode_assigned_email_promocode_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promoredemption",
            name="revoke_mode",
            field=models.CharField(
                blank=True,
                choices=[("", "—"), ("free", "Переведён на бесплатный тариф"), ("block", "Семья заблокирована")],
                default="",
                max_length=10,
            ),
        ),
    ]
