# Generated by Django 4.2.11 on 2026-08-16 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_alter_promoredemption_revoke_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40, unique=True)),
                ("title", models.CharField(max_length=100)),
                ("months", models.PositiveSmallIntegerField(help_text="На сколько месяцев продлевает подписку")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_offers",
                "indexes": [models.Index(fields=["plan_id", "is_active"], name="plan_offers_plan_id_5497d6_idx")],
            },
        ),
    ]
