# Generated by Django 6.0.3 on 2026-03-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_reason', models.TextField(blank=True)),
                ('request_number', models.CharField(blank=True, max_length=100)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_access_log',
            },
        ),
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('encrypted_data', models.BinaryField()),
                ('encryption_key_id', models.CharField(max_length=255)),
                ('retention_until', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_archive',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_type', models.CharField(choices=[('supplement', 'БАД'), ('food', 'Питание'), ('exercise', 'Упражнение'), ('other', 'Другое')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_type', models.CharField(choices=[('dietitian', 'Диетолог'), ('trainer', 'Тренер')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('archive_document_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specialists',
            },
        ),
        migrations.CreateModel(
            name='SpecialistAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активно'), ('ended', 'Завершено')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'specialist_assignments',
            },
        ),
    ]
