# Generated by Django 6.0.3 on 2026-03-24 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_families', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family.family'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['owner_id'], name='families_owner_i_339a52_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family_id'], name='family_memb_family__92fe93_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['user_id'], name='family_memb_user_id_526aa9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('family', 'user')},
        ),
    ]
