# Generated by Django 6.0.3 on 2026-03-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('menu', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='family.family'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menu'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.shoppinglist'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['family_id', 'status'], name='menus_family__46cf2c_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['start_date'], name='menus_start_d_7c0bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['creator_id'], name='menus_creator_06351a_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['menu_id'], name='menu_items_menu_id_4525cb_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['recipe_id'], name='menu_items_recipe__8357f1_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['member_id'], name='menu_items_member__1ef8b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('menu', 'member', 'day_offset', 'meal_type')},
        ),
        migrations.AddIndex(
            model_name='shoppingitem',
            index=models.Index(fields=['shopping_list_id', 'is_purchased'], name='shopping_it_shoppin_6cb9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingitem',
            index=models.Index(fields=['category'], name='shopping_it_categor_86d78f_idx'),
        ),
    ]
