# Generated by Django 4.2.11 on 2026-07-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Напр. «ИП Иванов Иван Иванович»",
                        max_length=255,
                        verbose_name="Наименование",
                    ),
                ),
                ("inn", models.CharField(blank=True, max_length=20, verbose_name="ИНН")),
                ("ogrnip", models.CharField(blank=True, max_length=20, verbose_name="ОГРНИП")),
                ("legal_address", models.CharField(blank=True, max_length=500, verbose_name="Адрес")),
                ("email", models.CharField(blank=True, max_length=255, verbose_name="E-mail")),
                ("phone", models.CharField(blank=True, max_length=64, verbose_name="Телефон")),
                ("bank_name", models.CharField(blank=True, max_length=255, verbose_name="Банк")),
                ("bank_bik", models.CharField(blank=True, max_length=20, verbose_name="БИК")),
                ("bank_account", models.CharField(blank=True, max_length=34, verbose_name="Расчётный счёт")),
                ("corr_account", models.CharField(blank=True, max_length=34, verbose_name="Корр. счёт")),
                ("requisites_extra", models.TextField(blank=True, verbose_name="Доп. реквизиты (свободный текст)")),
                ("offer_text", models.TextField(blank=True, verbose_name="Текст оферты")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="legal/", verbose_name="Логотип")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Юридическая информация",
                "verbose_name_plural": "Юридическая информация",
                "db_table": "legal_info",
            },
        ),
    ]
