# Generated by Django 4.2.11 on 2026-07-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalinfo",
            name="privacy_text",
            field=models.TextField(
                blank=True,
                help_text="Если оставить пустым — на сайте показывается типовой текст с вашими реквизитами.",
                verbose_name="Текст политики обработки ПД",
            ),
        ),
    ]
