# Generated by Django 4.2.11 on 2026-08-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0002_legalinfo_privacy_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="AndroidBuild",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "version_name",
                    models.CharField(help_text="Как в магазине: 1.0.2", max_length=32, verbose_name="Версия"),
                ),
                (
                    "version_code",
                    models.PositiveIntegerField(
                        blank=True, help_text="Номер сборки (versionCode)", null=True, verbose_name="Код версии"
                    ),
                ),
                ("file", models.FileField(upload_to="apk/", verbose_name="Файл")),
                ("size_bytes", models.PositiveBigIntegerField(default=0, verbose_name="Размер, байт")),
                ("sha256", models.CharField(blank=True, max_length=64, verbose_name="SHA-256")),
                ("notes", models.TextField(blank=True, verbose_name="Что нового")),
                ("is_published", models.BooleanField(default=True, verbose_name="Показывать на сайте")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Сборка Android",
                "verbose_name_plural": "Сборки Android",
                "db_table": "android_builds",
                "ordering": ["-created_at"],
            },
        ),
    ]
