# Generated by Django 4.2.11 on 2026-05-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fridge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
