# Generated by Django 4.2.11 on 2026-06-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fridge", "0004_seed_categories_and_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="popularity",
            field=models.CharField(blank=True, help_text="часто|средне|редко", max_length=16),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="department",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
