# Generated by Django 4.2.11 on 2026-06-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fridge", "0006_seed_rubricator"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="last_price_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
