# Generated by Django 4.2.11 on 2026-06-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fridge", "0012_fridgeitem_category_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="source",
            field=models.CharField(default="manual", help_text="manual|auto|import", max_length=16),
        ),
    ]
