# Generated by Django 4.2.11 on 2026-08-20 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0005_family_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fridge", "0015_product_owner_product_products_owner_i_8cc6ea_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner_family",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL = общий каталог (виден всем); иначе — продукт этой семьи.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="family.family",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Кто добавил. Видимость определяет «Семья-владелец».",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["owner_family"], name="products_owner_f_3668d9_idx"),
        ),
    ]
