# Generated by Django 4.2.11 on 2026-08-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fridge", "0017_products_to_families"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shelf_life_days",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Хранится после покупки, дней. Пусто — как у категории.", null=True
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="shelf_life_days",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Сколько хранится после покупки, дней. Пусто — не подставлять.", null=True
            ),
        ),
    ]
