# Generated by Django 4.2.11 on 2026-08-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fridge", "0019_seed_shelf_life"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Заведён вручную"),
                    ("auto", "Из ингредиентов рецепта"),
                    ("import", "Импорт"),
                    ("off", "Скан: OpenFoodFacts"),
                    ("ai", "Скан: догадка ИИ"),
                ],
                default="manual",
                help_text="Откуда взялась запись.",
                max_length=16,
            ),
        ),
    ]
