# Generated by Django 4.2.11 on 2026-08-22 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("family", "0006_family_auto_expiry"),
        ("fridge", "0021_alter_product_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyBarcode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("barcode", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_barcodes",
                        to="fridge.productcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_barcodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="barcodes", to="family.family"
                    ),
                ),
            ],
            options={
                "db_table": "family_barcodes",
                "indexes": [models.Index(fields=["barcode"], name="family_barc_barcode_f19426_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="familybarcode",
            constraint=models.UniqueConstraint(fields=("family", "barcode"), name="uniq_family_barcode"),
        ),
    ]
