# Generated by Django 4.2.11 on 2026-08-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fridge", "0022_familybarcode_familybarcode_uniq_family_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Заведён вручную"),
                    ("auto", "Из ингредиентов рецепта"),
                    ("import", "Импорт"),
                    ("off", "Скан: OpenFoodFacts"),
                    ("ai", "Скан: догадка ИИ"),
                    ("retail", "Каталог сети (штрих-коды)"),
                    ("off_bulk", "Справочник OpenFoodFacts"),
                ],
                default="manual",
                help_text="Откуда взялась запись.",
                max_length=16,
            ),
        ),
    ]
