# Generated by Django 4.2.11 on 2026-09-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0012_constructedmenu_applied_menu"),
        ("family", "0007_family_invite"),
        ("recipes", "0020_recipeimage"),
        ("fridge", "0025_product_skip_in_shopping"),
    ]

    operations = [
        migrations.CreateModel(
            name="FridgeWriteOff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[("cooked", "Приготовлено по меню"), ("manual", "Списано вручную")],
                        default="cooked",
                        max_length=16,
                    ),
                ),
                ("day_offset", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("meal_slot", models.CharField(blank=True, max_length=20)),
                ("created_by_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fridge_write_offs",
                        to="family.family",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="menu.menu",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "fridge_write_offs",
            },
        ),
        migrations.CreateModel(
            name="FridgeWriteOffLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("shortfall", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("shortfall_unit", models.CharField(blank=True, max_length=50)),
                (
                    "fridge_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="fridge.fridgeitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="fridge.product",
                    ),
                ),
                (
                    "write_off",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="fridge.fridgewriteoff"
                    ),
                ),
            ],
            options={
                "db_table": "fridge_write_off_lines",
                "indexes": [models.Index(fields=["write_off"], name="fridge_writ_write_o_6b22be_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="fridgewriteoff",
            index=models.Index(fields=["family", "created_at"], name="fridge_writ_family__e582ab_idx"),
        ),
        migrations.AddConstraint(
            model_name="fridgewriteoff",
            constraint=models.UniqueConstraint(
                condition=models.Q(("menu__isnull", False)),
                fields=("family", "menu", "day_offset", "meal_slot", "recipe"),
                name="uniq_fridge_writeoff_per_dish",
            ),
        ),
    ]
