# Generated by Django 4.2.11 on 2026-09-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fridge", "0026_fridgewriteoff_fridgewriteoffline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUnitWeight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unit", models.CharField(max_length=50)),
                (
                    "grams",
                    models.DecimalField(
                        decimal_places=2, help_text="Сколько граммов в одной такой единице", max_digits=10
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("seed", "Справочник"), ("manual", "Указано человеком"), ("ai", "Оценка модели")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="unit_weights", to="fridge.product"
                    ),
                ),
            ],
            options={
                "db_table": "product_unit_weights",
                "indexes": [models.Index(fields=["unit"], name="product_uni_unit_b6739e_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="productunitweight",
            constraint=models.UniqueConstraint(fields=("product", "unit"), name="uniq_product_unit_weight"),
        ),
    ]
