# Generated by Django 4.2.11 on 2026-09-26 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0007_family_invite"),
        ("fridge", "0027_productunitweight_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productunitweight",
            name="uniq_product_unit_weight",
        ),
        migrations.AddField(
            model_name="productunitweight",
            name="family",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — общий вес для всех. Задана — вес этой семьи, он перекрывает общий.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_weights",
                to="family.family",
                verbose_name="Семья",
            ),
        ),
        migrations.AddIndex(
            model_name="productunitweight",
            index=models.Index(fields=["family", "product"], name="product_uni_family__93cd32_idx"),
        ),
        migrations.AddConstraint(
            model_name="productunitweight",
            constraint=models.UniqueConstraint(
                condition=models.Q(("family__isnull", True)),
                fields=("product", "unit"),
                name="uniq_product_unit_weight_common",
            ),
        ),
        migrations.AddConstraint(
            model_name="productunitweight",
            constraint=models.UniqueConstraint(
                condition=models.Q(("family__isnull", False)),
                fields=("product", "unit", "family"),
                name="uniq_product_unit_weight_family",
            ),
        ),
    ]
