# Generated by Django 6.0.3 on 2026-03-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0002_initial'),
        ('family', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='family.familymember'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['member_id', 'date'], name='diary_entri_member__28cd4b_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['date', 'meal_type'], name='diary_entri_date_b921d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waterlog',
            unique_together={('member', 'date')},
        ),
    ]
