# Generated by Django 4.2.11 on 2026-06-03 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("family", "0004_remove_familymember_can_edit_menu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu", "0009_rb001_step4_component_role_dish_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("empty", "Пустой"),
                            ("menu", "Из меню"),
                            ("fridge", "Меню минус холодильник"),
                            ("ai_text", "Импорт из текста (ИИ)"),
                            ("csv", "Импорт из CSV"),
                        ],
                        default="empty",
                        max_length=16,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shopping_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_v2_lists",
                        to="family.family",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_v2_lists",
                        to="menu.menu",
                    ),
                ),
            ],
            options={
                "db_table": "shopping_v2_lists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseHistoryEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("source_list_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="purchase_history", to="family.family"
                    ),
                ),
                (
                    "purchased_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_history_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shopping_v2_history",
                "ordering": ["-purchased_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.BigIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("is_purchased", models.BooleanField(default=False)),
                ("purchased_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "purchased_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchased_shopping_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="shopping.shoppinglist"
                    ),
                ),
            ],
            options={
                "db_table": "shopping_v2_items",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(fields=["shopping_list_id", "is_purchased"], name="shopping_v2_shoppin_5738e5_idx"),
                    models.Index(fields=["category"], name="shopping_v2_categor_d44825_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("can_read", models.BooleanField(default=True)),
                ("can_toggle", models.BooleanField(default=False)),
                ("can_export", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="accesses", to="shopping.shoppinglist"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_list_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shopping_v2_access",
                "indexes": [models.Index(fields=["user_id"], name="shopping_v2_user_id_76f134_idx")],
                "unique_together": {("shopping_list", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="shoppinglist",
            index=models.Index(fields=["family_id", "is_archived"], name="shopping_v2_family__9ae283_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasehistoryentry",
            index=models.Index(fields=["family_id", "purchased_at"], name="shopping_v2_family__20c1fc_idx"),
        ),
    ]
