# Generated by Django 4.2.11 on 2026-06-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fridge", "0005_product_popularity_product_subcategory_and_more"),
        ("shopping", "0002_rename_legacy_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglistitem",
            name="category_fk",
            field=models.ForeignKey(
                blank=True,
                db_column="category_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shopping_items",
                to="fridge.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="shoppinglistitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_column="product_fk_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shopping_items",
                to="fridge.product",
            ),
        ),
    ]
