# Generated by Django 4.2.11 on 2026-06-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0003_shoppinglistitem_category_fk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasehistoryentry",
            name="price_per_unit",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="shoppinglistitem",
            name="price_per_unit",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
