# Generated by Django 6.0.3 on 2026-03-24 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0002_initial'),
        ('specialists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccesslog',
            name='accessed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='specialists.documentarchive'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='family.familymember'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentarchive',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='specialists.specialist'),
        ),
        migrations.AddField(
            model_name='specialistassignment',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_assignments', to='family.family'),
        ),
        migrations.AddField(
            model_name='specialistassignment',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='specialists.specialist'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='specialists.specialistassignment'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['document_id', 'accessed_at'], name='document_ac_documen_7e01cf_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['accessed_by_id'], name='document_ac_accesse_079539_idx'),
        ),
        migrations.AddIndex(
            model_name='specialist',
            index=models.Index(fields=['user_id'], name='specialists_user_id_5b59ba_idx'),
        ),
        migrations.AddIndex(
            model_name='specialist',
            index=models.Index(fields=['specialist_type', 'is_verified'], name='specialists_special_60f82d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentarchive',
            index=models.Index(fields=['specialist_id'], name='document_ar_special_7814e1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentarchive',
            index=models.Index(fields=['retention_until'], name='document_ar_retenti_871fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='specialistassignment',
            index=models.Index(fields=['family_id', 'status'], name='specialist__family__018adc_idx'),
        ),
        migrations.AddIndex(
            model_name='specialistassignment',
            index=models.Index(fields=['specialist_id', 'status'], name='specialist__special_769bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['assignment_id'], name='recommendat_assignm_86b65f_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['family_id', 'is_active'], name='recommendat_family__e705d4_idx'),
        ),
    ]
