# Generated by Django 4.2.11 on 2026-08-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0005_family_currency"),
        ("specialists", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialist",
            name="specialist_type",
            field=models.CharField(
                choices=[
                    ("dietitian", "Диетолог (нутрициолог)"),
                    ("trainer", "Фитнес-тренер"),
                    ("cook", "Личный повар"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SpecialistActionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section", models.CharField(max_length=20)),
                ("action", models.CharField(max_length=40)),
                ("summary", models.CharField(blank=True, default="", max_length=500)),
                ("object_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_actions",
                        to="family.family",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="family.familymember"
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="specialists.specialist"
                    ),
                ),
            ],
            options={
                "db_table": "specialist_action_log",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["family", "-created_at"], name="specialist__family__a9daf1_idx"),
                    models.Index(fields=["specialist", "-created_at"], name="specialist__special_e5c941_idx"),
                ],
            },
        ),
    ]
