# Generated by Django 4.2.11 on 2026-08-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_alter_promoredemption_revoke_mode"),
        ("specialists", "0003_alter_specialist_specialist_type_specialistactionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialistInviteCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_links",
                        to="subscriptions.promocode",
                    ),
                ),
                (
                    "specialist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_code",
                        to="specialists.specialist",
                    ),
                ),
            ],
            options={
                "db_table": "specialist_invite_codes",
                "indexes": [models.Index(fields=["promo"], name="specialist__promo_i_01cfb8_idx")],
            },
        ),
    ]
