# Generated by Django 4.2.11 on 2026-08-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0004_specialistinvitecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
