# Generated by Django 4.2.11 on 2026-04-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="can_edit_menu",
            field=models.BooleanField(default=False),
        ),
    ]
