# Generated by Django 4.2.11 on 2026-04-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0003_familymember_can_edit_menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familymember",
            name="can_edit_menu",
        ),
    ]
