# Generated by Django 4.2.11 on 2026-06-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0004_remove_familymember_can_edit_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="currency",
            field=models.CharField(default="RUB", max_length=8),
        ),
    ]
