# Generated by Django 4.2.11 on 2026-08-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0005_family_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="auto_expiry",
            field=models.BooleanField(
                default=True, help_text="Подставлять срок годности при переносе покупок в холодильник"
            ),
        ),
    ]
