# Generated by Django 4.2.11 on 2026-09-08 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("family", "0006_family_auto_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyInvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает ответа"),
                            ("accepted", "Принято"),
                            ("rejected", "Отклонено"),
                            ("cancelled", "Отозвано"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="family.family"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "family_invites",
                "indexes": [
                    models.Index(fields=["invited_user_id", "status"], name="family_invi_invited_35f1bb_idx"),
                    models.Index(fields=["family_id", "status"], name="family_invi_family__50a56b_idx"),
                ],
                "unique_together": {("family", "invited_user")},
            },
        ),
    ]
